package seed

import (
	"QuotesService/internal/models"
	"QuotesService/internal/provider"
	"log"
)

// Quotes is the pool of weather, nature, and science facts used to seed the database.
var Quotes = []string{
	"A bolt of lightning is five times hotter than the surface of the sun.",
	"Raindrops aren't actually tear-shaped; they look more like hamburger buns.",
	"Some clouds can weigh more than a million pounds.",
	"The highest wind speed ever recorded on Earth was 253 mph during a tropical cyclone.",
	"Snowflakes can take up to an hour to fall from a cloud to the ground.",
	"Antarctica is technically a desert and is the driest continent on Earth.",
	"A hurricane can release more energy in one second than 10 atomic bombs.",
	"You can tell the temperature by counting a cricket's chirps.",
	"Water can boil and freeze at the same time, a state called the 'triple point'.",
	"There is enough water in Earth's atmosphere to cover the entire planet in an inch of rain.",
	"Blood rain actually happened in India in 2001 due to red spores in the air.",
	"Dirt makes it rain; water vapor needs a particle of dust or dirt to condense around.",
	"The coldest temperature ever recorded on Earth was -128.6°F (-89.2°C) in Antarctica.",
	"Venus is the hottest planet in our solar system, with a surface temperature of over 860°F (460°C).",
	"A cubic mile of ordinary fog contains less than a gallon of water.",
	"Thunderstorms can produce antimatter.",
	"Cats and dogs have been known to sense approaching storms due to drops in barometric pressure.",
	"The moon has 'moonquakes' caused by the gravitational pull of the Earth.",
	"Earth's core is as hot as the surface of the sun.",
	"A typical hurricane produces the energy equivalent of half the world's electrical generating capacity.",
	"Worms really do come out of the ground when it rains to avoid drowning.",
	"The Atacama Desert in Chile is so dry that some weather stations have never recorded a single drop of rain.",
	"Lightning strikes the Earth about 100 times every second.",
	"Rainbows are actually completely circular; we only see a semi-circle from the ground.",
	"Sunsets on Mars appear blue.",
	"The smell of rain is called 'petrichor'.",
	"Tornadoes can be invisible; you only see them once they pick up dirt and debris.",
	"A single thunderstorm can hold over 200,000 tons of water.",
	"Polar bears have black skin underneath their white fur to absorb heat from the sun.",
	"The Earth's atmosphere is 78% nitrogen and 21% oxygen.",
	"Hailstones can be the size of grapefruits and fall at speeds over 100 mph.",
	"Trees can communicate with each other through an underground fungal network.",
	"The ozone layer smells like burning wire.",
	"Sound travels about four times faster in water than in air.",
	"The ocean contains 99% of the living space on the planet.",
	"There are 'ice volcanoes' on Pluto that erupt with a mixture of water and ice.",
	"The Great Red Spot on Jupiter is a giant storm that has been raging for hundreds of years.",
	"If Earth were the size of a billiard ball, it would be smoother than one.",
	"A day on Venus is longer than a year on Venus.",
	"Fulgurites are hollow tubes of glass formed when lightning strikes sand.",
	"The largest snowflake ever recorded was 15 inches wide and 8 inches thick.",
	"Fire whirls, or 'firenadoes', occur when intense heat and turbulent winds combine.",
	"The longest recorded lightning flash lasted for 16.73 seconds.",
	"About 2,000 thunderstorms are raining down on Earth at any given moment.",
	"Black ice is completely clear; it just looks black because of the road beneath it.",
	"The sun is 400 times larger than the moon, but it is also 400 times further away.",
	"Winds on Neptune can reach up to 1,200 mph.",
	"A 'sun dog' is an atmospheric phenomenon that creates the illusion of three suns in the sky.",
	"The Sahara Desert once snowed in 1979, 2016, and 2018.",
	"More people are allergic to cow's milk than any other food.",
	"The Earth is actually closest to the sun in January.",
	"A rainbow seen at night is called a 'moonbow'.",
	"Waterspouts are basically tornadoes that form over water.",
	"A typical cloud has a volume of about 1 cubic kilometer.",
	"Lightning tends to strike the tallest object in an area because it takes the path of least resistance.",
	"Volcanic lightning occurs when ash particles rub together during an eruption.",
	"A 'haboob' is a massive wall of dust created by thunderstorm downdrafts.",
	"You are more likely to be struck by lightning than to win the lottery.",
	"The highest temperature ever reliably recorded on Earth was 134°F (56.7°C) in Death Valley.",
	"Hurricanes spin counterclockwise in the Northern Hemisphere and clockwise in the Southern Hemisphere.",
	"The eye of a hurricane is mostly calm and clear.",
	"Animals migrate thousands of miles based on seasonal weather changes.",
	"A 'derecho' is a widespread, long-lived, straight-line wind storm.",
	"The Mariana Trench is the deepest part of the ocean, plunging over 36,000 feet down.",
	"Ocean currents are largely driven by the wind and the rotation of the Earth.",
	"El Niño is a climate pattern that describes the unusual warming of surface waters in the eastern Pacific.",
	"Lake effect snow happens when cold air moves over warmer lake water.",
	"Frost flowers are delicate ice crystals that form on thin plants in freezing weather.",
	"A blizzard must have winds of at least 35 mph and reduce visibility to less than a quarter-mile.",
	"The sky is blue because molecules in the air scatter blue light from the sun more than they scatter red light.",
	"A 'squall line' is a line of thunderstorms that can stretch for hundreds of miles.",
	"Monsoons are massive seasonal shifts in wind that bring heavy rains.",
	"The wettest place on Earth is Mawsynram, India, which gets about 467 inches of rain a year.",
	"Droughts are the most costly weather events in terms of agricultural damage.",
	"A 'supercell' is a highly organized thunderstorm with a deep, rotating updraft.",
	"Lightning can heat the air around it to 54,000°F (30,000°C).",
	"Thunder is the sound of air expanding rapidly due to the heat from lightning.",
	"The largest hailstone ever recorded in the US weighed 1.94 pounds.",
	"A flash flood can happen within minutes of excessive rainfall.",
	"Avalanches can reach speeds of up to 80 mph within seconds.",
	"The aurora borealis, or Northern Lights, is caused by solar wind interacting with Earth's magnetic field.",
	"Air is technically a fluid, just like water.",
	"The Coriolis effect is what causes large weather systems to rotate.",
	"Jet streams are fast-flowing, narrow air currents found in the atmosphere.",
	"A 'chinook' is a warm, dry wind that blows down the eastern slopes of the Rocky Mountains.",
	"The stratosphere contains the ozone layer, which absorbs most of the sun's ultraviolet radiation.",
	"A 'meteorologist' is a scientist who studies the weather.",
	"The first weather satellite, TIROS-1, was launched in 1960.",
	"Barometers measure atmospheric pressure to help predict the weather.",
	"Anemometers are used to measure wind speed.",
	"A 'microburst' is a localized column of sinking air within a thunderstorm.",
	"The Beaufort scale is used to estimate wind speed based on visual observations.",
	"Dew forms when moisture in the air condenses on cool surfaces overnight.",
	"Frost is simply dew that has frozen.",
	"Fog is basically a cloud that has formed at ground level.",
	"A 'whiteout' is a weather condition where visibility and contrast are severely reduced by snow.",
	"Sleet is rain that freezes into ice pellets before reaching the ground.",
	"Freezing rain is rain that remains liquid until it hits a freezing surface.",
	"Graupel, or soft hail, forms when supercooled water droplets coat a snowflake.",
	"A 'thundersnow' is a rare winter storm that features snow instead of rain along with thunder and lightning.",
	"The Fujita scale (now the Enhanced Fujita scale) measures the intensity of tornadoes.",
	"A 'bomb cyclone' is a storm that intensifies rapidly, with its central pressure dropping significantly in 24 hours.",
	"The term 'smog' was coined in the early 20th century as a blend of smoke and fog.",
	"Acid rain is caused by emissions of sulfur dioxide and nitrogen oxide.",
	"Global warming is increasing the frequency and intensity of extreme weather events.",
	"The greenhouse effect traps heat in the Earth's atmosphere.",
	"Carbon dioxide is the primary greenhouse gas emitted through human activities.",
	"The Earth's climate has changed constantly throughout its 4.5 billion-year history.",
	"Ice cores from glaciers can provide a record of Earth's past climate.",
	"A 'gale' is a very strong wind, typically between 34 and 47 knots.",
	"A 'zephyr' is a gentle, mild breeze.",
	"The doldrums are an area near the equator where prevailing winds are calm.",
	"The trade winds are steady, east-to-west winds that flow toward the equator.",
	"The roaring forties are strong westerly winds found in the Southern Hemisphere.",
	"A 'monsoon' comes from the Arabic word 'mausim', meaning season.",
	"The eye wall of a hurricane contains the strongest winds and heaviest rain.",
	"Storm surge is an abnormal rise of water generated by a storm.",
	"A 'typhoon' is exactly the same as a hurricane, just located in the Northwest Pacific.",
	"A 'cyclone' is the term used for hurricanes in the South Pacific and Indian Ocean.",
	"The Saffir-Simpson scale is used to rate the intensity of hurricanes.",
	"A 'watershed' is an area of land that drains all the streams and rainfall to a common outlet.",
	"An aquifer is an underground layer of water-bearing rock.",
	"The water cycle describes the continuous movement of water on, above, and below the surface of the Earth.",
	"Evaporation is the process of a liquid turning into a gas.",
	"Transpiration is the release of water vapor from plants into the atmosphere.",
	"Condensation is the process of a gas turning into a liquid.",
	"Precipitation is any form of water that falls from the sky.",
	"Sublimation is the transition of a substance directly from the solid to the gas phase.",
	"The albedo effect is a measure of how much sunlight is reflected by a surface.",
	"Ice and snow have a high albedo, reflecting most of the sun's energy.",
	"Oceans have a low albedo, absorbing most of the sun's energy.",
	"Permafrost is ground that remains completely frozen for at least two straight years.",
	"Glaciers hold about 69% of the world's freshwater.",
	"Sea ice forms from frozen seawater and floats on the ocean surface.",
	"An iceberg is a large piece of freshwater ice that has broken off a glacier or ice shelf.",
	"Only about 10% of an iceberg is visible above the water.",
	"A 'calving' event is when chunks of ice break off at the terminus of a glacier.",
	"The Earth's magnetic field protects us from solar wind and cosmic radiation.",
	"A geomagnetic storm is a major disturbance of Earth's magnetosphere caused by solar activity.",
	"Space weather can disrupt satellite communications and power grids.",
	"A solar flare is a sudden flash of increased brightness on the sun.",
	"A coronal mass ejection (CME) is a massive burst of solar wind and magnetic fields rising above the solar corona.",
	"The troposphere is the lowest layer of Earth's atmosphere and where weather happens.",
	"The mesosphere is where most meteors burn up upon entering the atmosphere.",
	"The thermosphere is where the International Space Station orbits.",
	"The exosphere is the outermost layer of Earth's atmosphere, fading into space.",
	"Air pressure decreases as altitude increases.",
	"A 'thermal' is a column of rising air in the lower altitudes of Earth's atmosphere.",
	"Birds and gliders use thermals to gain altitude without flapping or using an engine.",
}

// Run seeds the quotes table if it is empty. It is safe to call on every startup.
func Run(p provider.Provider) error {
	count, err := p.CountQuotes()
	if err != nil {
		return err
	}
	if count > 0 {
		log.Printf("Database already seeded with %d quotes, skipping", count)
		return nil
	}

	for _, text := range Quotes {
		if err := p.CreateQuote(&models.Quote{Text: text}); err != nil {
			return err
		}
	}

	log.Printf("Seeded %d quotes", len(Quotes))
	return nil
}
