basePath: /
definitions:
  QuotesService_internal_api_types.APIResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
    type: object
info:
  contact: {}
  description: A minimal service that serves random weather, nature, and science facts.
  title: Quotes Service API
  version: "1.0"
paths:
  /:
    get:
      description: Returns a random weather, nature, or science fact from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/QuotesService_internal_api_types.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/QuotesService_internal_api_types.APIResponse'
      summary: Get a random quote
      tags:
      - quotes
swagger: "2.0"
